import BeanSlider from '@/components/home/beanSlider/BeanSlider'
import Blogs from '@/components/home/blogs/Blogs';
import BrazilCoffee from '@/components/home/Brazil/BrazilCoffee';
import HandPicked from '@/components/home/handPicked/HandPicked';
import Head from 'next/head'
import Slider from '@/components/home/top-slider/Slider'
import Sponsors from '@/components/home/sponsors/Sponsors';
import Testimonials from '@/components/home/testimonials/Testimonials';
import Trending from '@/components/home/trending/Trending';
import background from "../public/images/Pattern.webp";
export default function Home() {
  return (
    <>
      <Head>
        <title>coffee shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='bg-no-repeat bg-cover' style={{backgroundImage: `url(${background.src})`}}>
        <Slider />
        <BeanSlider />
        <HandPicked />
        <BrazilCoffee />
        <Trending />
        <Testimonials />
        <Sponsors />
        <Blogs />
      </main>
    </>
  )
}
